# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\x05mini2\"R\n\x05Query\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x12\n\nchunk_size\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x05\"+\n\x0cShardRequest\x12\x1b\n\x05query\x18\x01 \x01(\x0b\x32\x0c.mini2.Query\"(\n\x07Segment\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0c\n\x04last\x18\x02 \x01(\x08\".\n\nShardReply\x12 \n\x08segments\x18\x01 \x03(\x0b\x32\x0e.mini2.Segment\"l\n\x0f\x41ggregatedReply\x12 \n\x08segments\x18\x01 \x03(\x0b\x32\x0e.mini2.Segment\x12\x10\n\x08\x63omplete\x18\x02 \x01(\x08\x12\x13\n\x0bnext_offset\x18\x03 \x01(\x05\x12\x10\n\x08has_more\x18\x04 \x01(\x08\x32>\n\x0bTeamService\x12/\n\x05\x46\x65tch\x12\x13.mini2.ShardRequest\x1a\x11.mini2.ShardReply2B\n\rLeaderService\x12\x31\n\tQueryOnce\x12\x0c.mini2.Query\x1a\x16.mini2.AggregatedReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERY']._serialized_start=24
  _globals['_QUERY']._serialized_end=106
  _globals['_SHARDREQUEST']._serialized_start=108
  _globals['_SHARDREQUEST']._serialized_end=151
  _globals['_SEGMENT']._serialized_start=153
  _globals['_SEGMENT']._serialized_end=193
  _globals['_SHARDREPLY']._serialized_start=195
  _globals['_SHARDREPLY']._serialized_end=241
  _globals['_AGGREGATEDREPLY']._serialized_start=243
  _globals['_AGGREGATEDREPLY']._serialized_end=351
  _globals['_TEAMSERVICE']._serialized_start=353
  _globals['_TEAMSERVICE']._serialized_end=415
  _globals['_LEADERSERVICE']._serialized_start=417
  _globals['_LEADERSERVICE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
